# -*- coding: utf-8 -*-
"""GRAD_CAM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mp6IeeVwSnQ-xC4bzphtWRZG62sPlwpv
"""

!pip install -q grad-cam



# ============================================================
# YOLOv8m RUN 4 - GRAD-CAM
# Qualitative Interpretability Analysis
# ============================================================

# Run this once if necessary:
# !pip install -q grad-cam

import os
import glob
import cv2
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

from ultralytics import YOLO
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image


# ============================================================
# 1. CONFIGURATION
# ============================================================

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

IMG_SIZE = 640
N_IMAGES = 8

TEST_IMAGES = "/content/dataset/test/images"
OUTPUT_DIR = "/content/gradcam_yolov8m_run4"

os.makedirs(OUTPUT_DIR, exist_ok=True)

print("=" * 70)
print("YOLOv8m RUN 4 - GRAD-CAM")
print("=" * 70)
print("Device:", DEVICE)


# ============================================================
# 2. FIND YOLOv8m RUN 4 WEIGHTS
# ============================================================

weight_matches = glob.glob(
    "/content/**/best_v8m_4.pt",
    recursive=True
)

if len(weight_matches) == 0:
    raise FileNotFoundError(
        "best_v8m_4.pt was not found under /content/"
    )

WEIGHT_PATH = weight_matches[0]

print("\nWeights:")
print(WEIGHT_PATH)


# ============================================================
# 3. LOAD YOLOv8 MODEL
# ============================================================

yolo = YOLO(WEIGHT_PATH)

model = yolo.model
model.to(DEVICE)
model.eval()

# Grad-CAM requires gradients
torch.set_grad_enabled(True)

for parameter in model.parameters():
    parameter.requires_grad_(True)

print("\nModel loaded successfully.")
print("Gradients enabled:", torch.is_grad_enabled())


# ============================================================
# 4. DISPLAY LAST MODEL LAYERS
# ============================================================

print("\nLast YOLOv8 layers:")
print("-" * 70)

start_index = max(0, len(model.model) - 6)

for i in range(start_index, len(model.model)):
    print(i, type(model.model[i]).__name__)


# ============================================================
# 5. SELECT TARGET LAYER
# ============================================================
#
# YOLOv8m:
# model.model[-1] = Detect head
# model.model[-2] = last C2f feature block
#
# We select the convolution inside the last C2f block so
# Grad-CAM receives a conventional 4-D feature map.
# ============================================================

target_layer = model.model[-2].cv2.conv

target_layers = [target_layer]

print("\nGrad-CAM target layer:")
print(target_layer)


# ============================================================
# 6. YOLOv8 WRAPPER
# ============================================================
#
# Grad-CAM normally expects a classification output.
# YOLOv8 is an object detector, so this wrapper extracts the
# class-response channels from the raw detector output.
#
# Output shape expected:
# [batch, 4 + number_of_classes, detections]
#
# First 4 channels = bounding-box information
# Remaining channels = class responses
# ============================================================

class YOLOv8GradCAMWrapper(nn.Module):

    def __init__(self, detector):
        super().__init__()
        self.detector = detector

    def forward(self, x):

        with torch.enable_grad():

            output = self.detector(x)

            # In evaluation mode YOLOv8 normally returns:
            # (predictions, raw_features)
            if isinstance(output, tuple):
                predictions = output[0]

            elif isinstance(output, list):
                predictions = output[0]

            else:
                predictions = output

            if predictions.ndim != 3:
                raise RuntimeError(
                    f"Unexpected YOLO output shape: "
                    f"{predictions.shape}"
                )

            # Remove bounding-box channels
            class_scores = predictions[:, 4:, :]

            # Strongest class response among all detections
            score = class_scores.amax(dim=2).amax(dim=1)

            return score


wrapped_model = YOLOv8GradCAMWrapper(model)

wrapped_model.to(DEVICE)
wrapped_model.eval()


# ============================================================
# 7. CUSTOM GRAD-CAM TARGET
# ============================================================
#
# We explicitly define the scalar response Grad-CAM should
# differentiate. This prevents pytorch-grad-cam from treating
# YOLO as a conventional image classifier.
# ============================================================

class YOLODetectionTarget:

    def __call__(self, model_output):

        return model_output.sum()


# ============================================================
# 8. FIND TEST IMAGES
# ============================================================

extensions = [
    "*.jpg",
    "*.jpeg",
    "*.png",
    "*.JPG",
    "*.JPEG",
    "*.PNG"
]

image_paths = []

for extension in extensions:

    image_paths.extend(
        glob.glob(
            os.path.join(
                TEST_IMAGES,
                extension
            )
        )
    )

image_paths = sorted(image_paths)

print("\nTest images found:", len(image_paths))

if len(image_paths) == 0:
    raise FileNotFoundError(
        f"No images were found in {TEST_IMAGES}"
    )


# ============================================================
# 9. SELECT REPRODUCIBLE IMAGE SUBSET
# ============================================================
#
# Images are selected at evenly spaced positions instead of
# random sampling so the selection can be reproduced.
# ============================================================

indices = np.linspace(
    0,
    len(image_paths) - 1,
    N_IMAGES,
    dtype=int
)

selected_images = [
    image_paths[index]
    for index in indices
]

print("\nSelected images:")

for i, path in enumerate(selected_images, start=1):

    print(
        f"{i}. {os.path.basename(path)}"
    )


# ============================================================
# 10. IMAGE PREPROCESSING
# ============================================================

def prepare_image(image_path):

    image_bgr = cv2.imread(image_path)

    if image_bgr is None:
        raise ValueError(
            f"Could not read image: {image_path}"
        )

    image_rgb = cv2.cvtColor(
        image_bgr,
        cv2.COLOR_BGR2RGB
    )

    image_rgb = cv2.resize(
        image_rgb,
        (IMG_SIZE, IMG_SIZE)
    )

    image_float = (
        image_rgb.astype(np.float32) / 255.0
    )

    input_tensor = torch.from_numpy(
        image_float
    ).permute(
        2, 0, 1
    ).unsqueeze(0)

    input_tensor = input_tensor.to(device)
    input_tensor.requires_grad_(True)

    input_tensor.requires_grad_(True)

    return image_float, input_tensor


# ============================================================
# 11. VERIFY GRADIENT GRAPH
# ============================================================

print("\n" + "=" * 70)
print("VERIFYING GRADIENT GRAPH")
print("=" * 70)

test_rgb, test_tensor = prepare_image(
    selected_images[0]
)

test_output = wrapped_model(
    test_tensor
)

print("Output:", test_output)
print("Output shape:", test_output.shape)
print("requires_grad:", test_output.requires_grad)
print("grad_fn:", test_output.grad_fn)

if not test_output.requires_grad:

    raise RuntimeError(
        "The YOLO output does not have an active "
        "gradient graph."
    )

print("\nGradient graph: OK")


# ============================================================
# 12. INITIALIZE GRAD-CAM
# ============================================================

cam = GradCAM(
    model=wrapped_model,
    target_layers=target_layers
)

targets = [
    YOLODetectionTarget()
]


# ============================================================
# 13. GENERATE GRAD-CAM MAPS
# ============================================================

generated_files = []

print("\n" + "=" * 70)
print("GENERATING GRAD-CAM MAPS")
print("=" * 70)

for number, image_path in enumerate(
    selected_images,
    start=1
):

    print(
        f"\n[{number}/{len(selected_images)}] "
        f"{os.path.basename(image_path)}"
    )

    # --------------------------------------------------------
    # Prepare image
    # --------------------------------------------------------

    rgb_image, input_tensor = prepare_image(
        image_path
    )

    # Clear previous gradients
    wrapped_model.zero_grad(set_to_none=True)

    # --------------------------------------------------------
    # Grad-CAM
    # --------------------------------------------------------

    grayscale_cam = cam(
        input_tensor=input_tensor,
        targets=targets
    )

    grayscale_cam = grayscale_cam[0]

    # --------------------------------------------------------
    # Overlay heatmap
    # --------------------------------------------------------

    visualization = show_cam_on_image(
        rgb_image,
        grayscale_cam,
        use_rgb=True
    )

    # --------------------------------------------------------
    # Save heatmap
    # --------------------------------------------------------

    base_name = os.path.splitext(
        os.path.basename(image_path)
    )[0]

    output_path = os.path.join(
        OUTPUT_DIR,
        f"{number:02d}_{base_name}_gradcam.png"
    )

    cv2.imwrite(
        output_path,
        cv2.cvtColor(
            visualization,
            cv2.COLOR_RGB2BGR
        )
    )

    generated_files.append(
        output_path
    )

    print("Saved:", output_path)


# ============================================================
# 14. DISPLAY ORIGINAL + GRAD-CAM
# ============================================================

print("\n" + "=" * 70)
print("GRAD-CAM RESULTS")
print("=" * 70)

for original_path, cam_path in zip(
    selected_images,
    generated_files
):

    original = cv2.imread(
        original_path
    )

    original = cv2.cvtColor(
        original,
        cv2.COLOR_BGR2RGB
    )

    cam_image = cv2.imread(
        cam_path
    )

    cam_image = cv2.cvtColor(
        cam_image,
        cv2.COLOR_BGR2RGB
    )

    plt.figure(
        figsize=(10, 4)
    )

    # Original
    plt.subplot(1, 2, 1)

    plt.imshow(original)

    plt.axis("off")

    plt.title(
        "Original"
    )

    # Grad-CAM
    plt.subplot(1, 2, 2)

    plt.imshow(cam_image)

    plt.axis("off")

    plt.title(
        "YOLOv8m - Grad-CAM"
    )

    plt.tight_layout()

    plt.show()


# ============================================================
# 15. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("GRAD-CAM COMPLETED")
print("=" * 70)

print(
    "Images analyzed:",
    len(selected_images)
)

print(
    "Grad-CAM maps generated:",
    len(generated_files)
)

print(
    "Output directory:",
    OUTPUT_DIR
)



# ============================================================
# YOLOv8m RUN 4
# GRAD-CAM - LAYER 15
# VERIFICATION ON SAME 8 TEST IMAGES
# ============================================================

import os
import cv2
import torch
import numpy as np
import matplotlib.pyplot as plt

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image


# ============================================================
# 1. CONFIGURATION
# ============================================================

OUTPUT_DIR_L15 = "/content/gradcam_v8m_layer15"

os.makedirs(
    OUTPUT_DIR_L15,
    exist_ok=True
)

# Enable gradients globally
torch.set_grad_enabled(True)

# Enable gradients for all model parameters
for param in model.parameters():
    param.requires_grad_(True)

model.eval()
wrapped_model.eval()

# Layer selected after layer-comparison experiment
TARGET_LAYER = model.model[15].cv2.conv

# Class names
CLASS_NAMES = yolo.names


print("=" * 70)
print("YOLOv8m RUN 4 - GRAD-CAM LAYER 15")
print("=" * 70)

print("\nTarget layer:")
print(TARGET_LAYER)

print("\nImages to analyze:")
print(len(selected_images))

print("\nClasses:")
print(CLASS_NAMES)


# ============================================================
# 2. INITIALIZE GRAD-CAM
# ============================================================

cam = GradCAM(
    model=wrapped_model,
    target_layers=[TARGET_LAYER]
)


# ============================================================
# 3. STORAGE
# ============================================================

generated_layer15 = []

# Raw results used later for final Fig. 6
gradcam_v8_results = []


# ============================================================
# 4. PROCESS SAME 8 TEST IMAGES
# ============================================================

for number, image_path in enumerate(
    selected_images,
    start=1
):

    print("\n" + "-" * 70)

    print(
        f"[{number}/{len(selected_images)}] "
        f"{os.path.basename(image_path)}"
    )


    # --------------------------------------------------------
    # A. STANDARD YOLOv8 DETECTION
    # --------------------------------------------------------

    results = yolo.predict(
        source=image_path,
        imgsz=640,
        conf=0.25,
        iou=0.60,
        verbose=False
    )

    result = results[0]

    if (
        result.boxes is None
        or len(result.boxes) == 0
    ):

        print(
            "No detection found - skipped."
        )

        continue


    # --------------------------------------------------------
    # B. HIGHEST-CONFIDENCE DETECTION
    # --------------------------------------------------------

    confidences = (
        result.boxes.conf
        .detach()
        .cpu()
        .numpy()
    )

    best_index = int(
        np.argmax(confidences)
    )

    best_box = result.boxes[
        best_index
    ]

    class_id = int(
        best_box.cls.item()
    )

    confidence = float(
        best_box.conf.item()
    )

    class_name = CLASS_NAMES[
        class_id
    ]


    print(
        f"Selected detection: "
        f"{class_name} | "
        f"confidence={confidence:.3f}"
    )


    # --------------------------------------------------------
    # C. PREPARE IMAGE
    # --------------------------------------------------------

    (
        original_rgb,
        input_rgb,
        input_tensor,
        ratio,
        padding
    ) = prepare_image(
        image_path
    )


    # --------------------------------------------------------
    # IMPORTANT:
    # Enable gradient tracking for Grad-CAM
    # --------------------------------------------------------

    input_tensor = (
        input_tensor
        .clone()
        .detach()
        .requires_grad_(True)
    )


    # --------------------------------------------------------
    # D. CLASS-CONDITIONED TARGET
    # --------------------------------------------------------

    targets = [
        YOLOClassDetectionTarget(
            class_id
        )
    ]


    # Clear previous gradients
    wrapped_model.zero_grad(
        set_to_none=True
    )


    # --------------------------------------------------------
    # E. GRAD-CAM
    # --------------------------------------------------------

    with torch.enable_grad():

        grayscale_cam = cam(
            input_tensor=input_tensor,
            targets=targets
        )[0]


    # --------------------------------------------------------
    # F. CREATE OVERLAY
    # --------------------------------------------------------

    cam_overlay = show_cam_on_image(
        input_rgb,
        grayscale_cam,
        use_rgb=True
    )


    # --------------------------------------------------------
    # G. STORE RAW RESULT
    # FOR FINAL IJACSA FIG. 6
    # --------------------------------------------------------

    gradcam_v8_results.append(
        {
            "number": number,
            "image_path": image_path,

            "original":
                original_rgb.copy(),

            "gradcam":
                cam_overlay.copy(),

            "class_id":
                class_id,

            "class_name":
                class_name,

            "confidence":
                confidence
        }
    )


    # --------------------------------------------------------
    # H. SAVE INDIVIDUAL GRAD-CAM
    # --------------------------------------------------------

    base_name = os.path.splitext(
        os.path.basename(
            image_path
        )
    )[0]


    cam_path = os.path.join(
        OUTPUT_DIR_L15,

        f"{number:02d}_"
        f"{base_name}_"
        f"{class_name}_"
        f"L15_gradcam.png"
    )


    cv2.imwrite(
        cam_path,

        cv2.cvtColor(
            cam_overlay,
            cv2.COLOR_RGB2BGR
        )
    )


    # --------------------------------------------------------
    # I. ORIGINAL + GRAD-CAM
    # VERIFICATION ONLY
    # --------------------------------------------------------

    fig, axes = plt.subplots(
        1,
        2,
        figsize=(10, 5)
    )


    axes[0].imshow(
        original_rgb
    )

    axes[0].set_title(
        "Original"
    )

    axes[0].axis(
        "off"
    )


    axes[1].imshow(
        cam_overlay
    )

    axes[1].set_title(
        f"Grad-CAM - Layer 15\n"
        f"Target: "
        f"{class_name} "
        f"({confidence:.2f})"
    )

    axes[1].axis(
        "off"
    )


    plt.tight_layout()


    comparison_path = os.path.join(
        OUTPUT_DIR_L15,

        f"{number:02d}_"
        f"{base_name}_"
        f"comparison.png"
    )


    plt.savefig(
        comparison_path,
        dpi=300,
        bbox_inches="tight"
    )


    plt.close(fig)


    generated_layer15.append(
        comparison_path
    )


    print(
        "Saved:",
        cam_path
    )


# ============================================================
# 5. RELEASE GRAD-CAM HOOKS
# ============================================================

cam.activations_and_grads.release()


# ============================================================
# 6. DISPLAY ALL 8 RESULTS
# VERIFICATION FIGURE ONLY
# ============================================================

print("\n" + "=" * 70)
print("DISPLAYING YOLOv8m RESULTS")
print("=" * 70)


n_results = len(
    gradcam_v8_results
)


fig, axes = plt.subplots(
    2,
    4,
    figsize=(16, 8)
)

axes = axes.flatten()


for i, result_data in enumerate(
    gradcam_v8_results[:8]
):

    axes[i].imshow(
        result_data["gradcam"]
    )

    axes[i].set_title(
        f'Example '
        f'{result_data["number"]}\n'
        f'{result_data["class_name"]}'
    )

    axes[i].axis(
        "off"
    )


# Disable unused panels
for j in range(
    min(n_results, 8),
    len(axes)
):

    axes[j].axis(
        "off"
    )


plt.tight_layout()


SUMMARY_PATH = (
    "/content/"
    "YOLOv8m_Layer15_"
    "GradCAM_8images.png"
)


plt.savefig(
    SUMMARY_PATH,
    dpi=300,
    bbox_inches="tight"
)


plt.show()

plt.close(fig)


# ============================================================
# 7. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("YOLOv8m LAYER 15 VERIFICATION COMPLETED")
print("=" * 70)


print(
    "Images requested:",
    len(selected_images)
)

print(
    "Grad-CAM results generated:",
    len(gradcam_v8_results)
)

print(
    "Individual results:",
    OUTPUT_DIR_L15
)

print(
    "Summary figure:",
    SUMMARY_PATH
)


print("\nGenerated results:")

for r in gradcam_v8_results:

    print(
        f'Example {r["number"]}: '
        f'{r["class_name"]} | '
        f'confidence='
        f'{r["confidence"]:.3f} | '
        f'{os.path.basename(r["image_path"])}'
    )



# ============================================================
# YOLOv5m RUN 4
# COMPLETE SETUP FOR GRAD-CAM
# Original Ultralytics YOLOv5 repository
# ============================================================

import os
import sys
import torch
import numpy as np
import cv2


# ============================================================
# 1. YOLOv5 REPOSITORY
# ============================================================

YOLOV5_DIR = "/content/yolov5"

if not os.path.exists(YOLOV5_DIR):
    !git clone -q https://github.com/ultralytics/yolov5.git /content/yolov5

# Add repository to Python path
if YOLOV5_DIR not in sys.path:
    sys.path.insert(0, YOLOV5_DIR)

print("YOLOv5 repository ready.")


# ============================================================
# 2. INSTALL YOLOv5 REQUIREMENTS
# ============================================================

!pip install -q -r /content/yolov5/requirements.txt


# ============================================================
# 3. IMPORT YOLOv5 MODULES
# ============================================================

from models.common import DetectMultiBackend
from utils.general import non_max_suppression
from utils.augmentations import letterbox


# ============================================================
# 4. WEIGHTS
# ============================================================

V5M_PATH = (
    "/content/ENTRENAMIENTOS_PT_VF/"
    "ENTRENAMIENTOS_PT_VF/"
    "ENTRENAMIENTOS_PT/"
    "best_v5m_4.pt"
)

assert os.path.exists(V5M_PATH), (
    f"Weights not found:\n{V5M_PATH}"
)

print("Weights found:")
print(V5M_PATH)


# ============================================================
# 5. DEVICE
# ============================================================

device_v5 = torch.device(
    "cuda:0"
    if torch.cuda.is_available()
    else "cpu"
)

print("\nDevice:", device_v5)


# ============================================================
# 6. LOAD YOLOv5m RUN 4
# ============================================================

backend_v5 = DetectMultiBackend(
    V5M_PATH,
    device=device_v5,
    fp16=False
)

# Raw PyTorch model
model_v5 = backend_v5.model

model_v5.to(device_v5)
model_v5.float()
model_v5.eval()


# ============================================================
# 7. ENABLE GRADIENTS
# ============================================================

torch.set_grad_enabled(True)

for parameter in model_v5.parameters():
    parameter.requires_grad_(True)


# ============================================================
# 8. CLASS NAMES
# ============================================================

CLASS_NAMES_V5 = backend_v5.names

print("\nClasses:")
print(CLASS_NAMES_V5)


# ============================================================
# 9. VERIFY MODEL STRUCTURE
# ============================================================

print("\n" + "=" * 70)
print("YOLOv5m RUN 4 MODEL")
print("=" * 70)

print("Model type:")
print(type(model_v5))

print("\nNumber of model modules:")
print(len(model_v5.model))


# ============================================================
# 10. VERIFY LAYER 20
# ============================================================

print("\n" + "=" * 70)
print("LAYER 20")
print("=" * 70)

print(model_v5.model[20])


# ============================================================
# 11. GRAD-CAM TARGET LAYER
# ============================================================

TARGET_LAYER_V5 = model_v5.model[20].cv3.conv

print("\nGrad-CAM target layer:")
print(TARGET_LAYER_V5)


# ============================================================
# 12. VERIFY SAME 8 TEST IMAGES
# ============================================================

selected_images_v5 = selected_images.copy()

print("\n" + "=" * 70)
print("SELECTED TEST IMAGES")
print("=" * 70)

print("Number of images:", len(selected_images_v5))

for i, path in enumerate(
    selected_images_v5,
    start=1
):
    print(
        f"{i}: {os.path.basename(path)}"
    )


# ============================================================
# 13. FINAL CHECK
# ============================================================

print("\n" + "=" * 70)
print("YOLOv5m RUN 4 READY FOR GRAD-CAM")
print("=" * 70)

print("Weights: best_v5m_4.pt")
print("Target module: model_v5.model[20]")
print("Target convolution: model_v5.model[20].cv3.conv")
print("Images:", len(selected_images_v5))
print("Gradients enabled:", torch.is_grad_enabled())



# ============================================================
# YOLOv5m RUN 4
# GRAD-CAM - LAYER 20
# SAME 8 TEST IMAGES USED FOR YOLOv8m
# ============================================================

import os
import cv2
import torch
import numpy as np
import matplotlib.pyplot as plt

from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image

from utils.general import non_max_suppression
from utils.augmentations import letterbox


# ============================================================
# 1. CLEAN PREVIOUS FIGURES
# ============================================================

plt.close("all")


# ============================================================
# 2. CONFIGURATION
# ============================================================

OUTPUT_DIR_V5 = "/content/gradcam_v5m_layer20"

os.makedirs(
    OUTPUT_DIR_V5,
    exist_ok=True
)

torch.set_grad_enabled(True)

for parameter in model_v5.parameters():
    parameter.requires_grad_(True)

model_v5.eval()

TARGET_LAYER_V5 = model_v5.model[20].cv3.conv

print("=" * 70)
print("YOLOv5m RUN 4 - GRAD-CAM LAYER 20")
print("=" * 70)

print("\nTarget layer:")
print(TARGET_LAYER_V5)

print("\nImages to analyze:")
print(len(selected_images_v5))

print("\nClasses:")
print(CLASS_NAMES_V5)


# ============================================================
# 3. PREPARE IMAGE FUNCTION
# ============================================================

def prepare_v5_image(image_path, imgsz=640):

    # Read image
    image_bgr = cv2.imread(image_path)

    if image_bgr is None:
        raise FileNotFoundError(
            f"Could not read image: {image_path}"
        )

    # BGR -> RGB
    original_rgb = cv2.cvtColor(
        image_bgr,
        cv2.COLOR_BGR2RGB
    )

    # YOLOv5 letterbox
    letterboxed = letterbox(
        original_rgb,
        new_shape=imgsz,
        stride=32,
        auto=False
    )[0]

    # Float image for CAM overlay
    input_rgb = (
        letterboxed.astype(np.float32)
        / 255.0
    )

    # HWC -> CHW
    tensor = np.transpose(
        input_rgb,
        (2, 0, 1)
    )

    tensor = np.ascontiguousarray(
        tensor
    )

    # NumPy -> Torch
    input_tensor = torch.from_numpy(
        tensor
    ).float()

    # Add batch dimension
    input_tensor = input_tensor.unsqueeze(0)

    # Device
    input_tensor = input_tensor.to(
        device_v5
    )

    # IMPORTANT FOR GRAD-CAM
    input_tensor = (
        input_tensor
        .clone()
        .detach()
        .requires_grad_(True)
    )

    return (
        original_rgb,
        input_rgb,
        input_tensor
    )


# ============================================================
# 4. YOLOv5 WRAPPER FOR GRAD-CAM
# ============================================================

class YOLOv5Wrapper(torch.nn.Module):

    def __init__(self, model):
        super().__init__()
        self.model = model

    def forward(self, x):

        output = self.model(x)

        # YOLOv5 inference usually returns:
        # (prediction, feature outputs)
        if isinstance(output, (list, tuple)):
            output = output[0]

        return output


wrapped_v5 = YOLOv5Wrapper(
    model_v5
)

wrapped_v5.eval()


# ============================================================
# 5. GRAD-CAM TARGET
#
# YOLOv5 output:
# [x, y, w, h, objectness, class scores...]
#
# Target =
# maximum objectness * class probability response
# for selected class.
# ============================================================

class YOLOv5ClassTarget:

    def __init__(self, class_id):
        self.class_id = class_id

    def __call__(self, model_output):

        if model_output.ndim == 3:
            model_output = model_output[0]

        objectness = model_output[:, 4]

        class_score = model_output[
            :,
            5 + self.class_id
        ]

        score = (
            objectness *
            class_score
        )

        return score.max()


# ============================================================
# 6. FUNCTION TO OBTAIN HIGHEST-CONFIDENCE DETECTION
# ============================================================

def get_main_detection_v5(
    image_path,
    conf_thres=0.25,
    iou_thres=0.60
):

    (
        original_rgb,
        input_rgb,
        input_tensor
    ) = prepare_v5_image(
        image_path
    )

    # Detection does not need gradients
    with torch.no_grad():

        prediction = model_v5(
            input_tensor
        )

        if isinstance(
            prediction,
            (list, tuple)
        ):
            prediction = prediction[0]


        detections = non_max_suppression(
            prediction,
            conf_thres=conf_thres,
            iou_thres=iou_thres
        )


    detection = detections[0]

    if (
        detection is None
        or len(detection) == 0
    ):
        return None


    # YOLOv5 NMS output:
    # x1, y1, x2, y2, confidence, class

    best_index = torch.argmax(
        detection[:, 4]
    )

    best_detection = detection[
        best_index
    ]


    confidence = float(
        best_detection[4].item()
    )

    class_id = int(
        best_detection[5].item()
    )

    bbox = (
        best_detection[:4]
        .detach()
        .cpu()
        .numpy()
    )


    return {
        "class_id": class_id,
        "confidence": confidence,
        "bbox": bbox
    }


# ============================================================
# 7. INITIALIZE GRAD-CAM
# ============================================================

cam_v5 = GradCAM(
    model=wrapped_v5,
    target_layers=[TARGET_LAYER_V5]
)


# ============================================================
# 8. STORAGE
# ============================================================

gradcam_v5_results = []

generated_v5 = []


# ============================================================
# 9. PROCESS SAME 8 IMAGES
# ============================================================

for number, image_path in enumerate(
    selected_images_v5,
    start=1
):

    print("\n" + "-" * 70)

    print(
        f"[{number}/{len(selected_images_v5)}] "
        f"{os.path.basename(image_path)}"
    )


    # --------------------------------------------------------
    # A. MAIN YOLOv5 DETECTION
    # --------------------------------------------------------

    detection = get_main_detection_v5(
        image_path,
        conf_thres=0.25,
        iou_thres=0.60
    )


    if detection is None:

        print(
            "No detection found - skipped."
        )

        continue


    class_id = detection[
        "class_id"
    ]

    confidence = detection[
        "confidence"
    ]

    bbox = detection[
        "bbox"
    ]

    class_name = CLASS_NAMES_V5[
        class_id
    ]


    print(
        f"Selected detection: "
        f"{class_name} | "
        f"confidence={confidence:.3f}"
    )


    # --------------------------------------------------------
    # B. PREPARE IMAGE FOR GRAD-CAM
    # --------------------------------------------------------

    (
        original_rgb,
        input_rgb,
        input_tensor
    ) = prepare_v5_image(
        image_path
    )


    # Extra safety:
    # guarantee gradient tracking
    input_tensor = (
        input_tensor
        .clone()
        .detach()
        .requires_grad_(True)
    )


    # --------------------------------------------------------
    # C. CLASS-CONDITIONED TARGET
    # --------------------------------------------------------

    targets = [
        YOLOv5ClassTarget(
            class_id
        )
    ]


    wrapped_v5.zero_grad(
        set_to_none=True
    )


    # --------------------------------------------------------
    # D. GRAD-CAM
    # --------------------------------------------------------

    with torch.enable_grad():

        grayscale_cam = cam_v5(
            input_tensor=input_tensor,
            targets=targets
        )[0]


    # --------------------------------------------------------
    # E. CREATE OVERLAY
    # --------------------------------------------------------

    cam_overlay = show_cam_on_image(
        input_rgb,
        grayscale_cam,
        use_rgb=True
    )


    # --------------------------------------------------------
    # F. STORE RAW RESULT
    # --------------------------------------------------------

    gradcam_v5_results.append(
        {
            "number": number,

            "image_path":
                image_path,

            "original":
                original_rgb.copy(),

            "gradcam":
                cam_overlay.copy(),

            "class_id":
                class_id,

            "class_name":
                class_name,

            "confidence":
                confidence,

            "bbox":
                bbox
        }
    )


    # --------------------------------------------------------
    # G. SAVE INDIVIDUAL GRAD-CAM
    # --------------------------------------------------------

    base_name = os.path.splitext(
        os.path.basename(
            image_path
        )
    )[0]


    cam_path = os.path.join(
        OUTPUT_DIR_V5,

        f"{number:02d}_"
        f"{base_name}_"
        f"{class_name}_"
        f"L20_gradcam.png"
    )


    cv2.imwrite(
        cam_path,

        cv2.cvtColor(
            cam_overlay,
            cv2.COLOR_RGB2BGR
        )
    )


    # --------------------------------------------------------
    # H. SAVE ORIGINAL + GRAD-CAM
    # Verification only
    # --------------------------------------------------------

    fig, axes = plt.subplots(
        1,
        2,
        figsize=(10, 5)
    )


    axes[0].imshow(
        original_rgb
    )

    axes[0].set_title(
        "Original"
    )

    axes[0].axis(
        "off"
    )


    axes[1].imshow(
        cam_overlay
    )

    axes[1].set_title(
        f"Grad-CAM - Layer 20\n"
        f"Target: "
        f"{class_name} "
        f"({confidence:.2f})"
    )

    axes[1].axis(
        "off"
    )


    plt.tight_layout()


    comparison_path = os.path.join(
        OUTPUT_DIR_V5,

        f"{number:02d}_"
        f"{base_name}_"
        f"comparison.png"
    )


    plt.savefig(
        comparison_path,
        dpi=300,
        bbox_inches="tight"
    )

    plt.close(fig)


    generated_v5.append(
        comparison_path
    )


    print(
        "Saved:",
        cam_path
    )


# ============================================================
# 10. RELEASE GRAD-CAM HOOKS
# ============================================================

cam_v5.activations_and_grads.release()


# ============================================================
# 11. DISPLAY ALL 8 RESULTS
# ============================================================

print("\n" + "=" * 70)
print("DISPLAYING YOLOv5m RESULTS")
print("=" * 70)


n_results = len(
    gradcam_v5_results
)


fig, axes = plt.subplots(
    2,
    4,
    figsize=(16, 8)
)

axes = axes.flatten()


for i, result_data in enumerate(
    gradcam_v5_results[:8]
):

    axes[i].imshow(
        result_data["gradcam"]
    )

    axes[i].set_title(
        f'Example '
        f'{result_data["number"]}\n'
        f'{result_data["class_name"]}'
    )

    axes[i].axis(
        "off"
    )


for j in range(
    min(n_results, 8),
    len(axes)
):

    axes[j].axis(
        "off"
    )


plt.tight_layout()


SUMMARY_V5_PATH = (
    "/content/"
    "YOLOv5m_Layer20_"
    "GradCAM_8images.png"
)


plt.savefig(
    SUMMARY_V5_PATH,
    dpi=300,
    bbox_inches="tight"
)


plt.show()

plt.close(fig)


# ============================================================
# 12. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("YOLOv5m LAYER 20 VERIFICATION COMPLETED")
print("=" * 70)

print(
    "Images requested:",
    len(selected_images_v5)
)

print(
    "Grad-CAM results generated:",
    len(gradcam_v5_results)
)

print(
    "Individual results:",
    OUTPUT_DIR_V5
)

print(
    "Summary figure:",
    SUMMARY_V5_PATH
)


print("\nGenerated results:")

for r in gradcam_v5_results:

    print(
        f'Example {r["number"]}: '
        f'{r["class_name"]} | '
        f'confidence='
        f'{r["confidence"]:.3f} | '
        f'{os.path.basename(r["image_path"])}'
    )