# -*- coding: utf-8 -*-
"""YOLOV5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h6L0mBVR5S-6LRPXHZQ54wyc9HBSKU_S
"""

# Commented out IPython magic to ensure Python compatibility.
# ============================================================
# YOLOv5 n/s/m - SEED 0
# TRAINING PIPELINE
# ============================================================

# SECURITY NOTE:
# Set ROBOFLOW_API_KEY, ROBOFLOW_WORKSPACE and ROBOFLOW_PROJECT
# as environment variables before running.
# Credentials from the original research code were intentionally removed.

# -*- coding: utf-8 -*-


# ============================================================
# 0. INSTALL
# ============================================================

!git clone https://github.com/ultralytics/yolov5.git

# %cd yolov5

!git checkout -q b8493964

!pip install -q -r requirements.txt
!pip install -q roboflow


# ============================================================
# 1. ROBOFLOW DATASET
# ============================================================

import os
from roboflow import Roboflow

rf = Roboflow(
    api_key=os.environ["ROBOFLOW_API_KEY"]
)

project = rf.workspace(
    os.environ["ROBOFLOW_WORKSPACE"]
).project(
    os.environ["ROBOFLOW_PROJECT"]
)

version = project.version(
    int(os.environ.get("ROBOFLOW_VERSION", "1"))
)

dataset = version.download("yolov5")

DATA_YAML = f"{dataset.location}/data.yaml"


# ============================================================
# 2. DISABLE WANDB
# ============================================================

os.environ["WANDB_MODE"] = "disabled"


# ============================================================
# 3. EXPERIMENT CONFIGURATION
# ============================================================

MODELS = {
    "YOLOv5n": "yolov5n.pt",
    "YOLOv5s": "yolov5s.pt",
    "YOLOv5m": "yolov5m.pt",
}

SEED = 0

EPOCHS = 50
IMGSZ = 640
BATCH = 16

OPTIMIZER = "SGD"


# ============================================================
# 4. PRINT CONFIGURATION
# ============================================================

print("=" * 80)
print("YOLOv5 TRAINING CONFIGURATION")
print("=" * 80)

print("\nModels:")
for model_name, weights in MODELS.items():
    print(f"  {model_name}: {weights}")

print("\nSeed       :", SEED)
print("Epochs     :", EPOCHS)
print("Image size :", IMGSZ)
print("Batch      :", BATCH)
print("Optimizer  :", OPTIMIZER)
print("Dataset    :", DATA_YAML)

print("=" * 80)


# ============================================================
# 5. TRAINING LOOP
# ============================================================

for model_name, weights in MODELS.items():

    run_name = f"{model_name}_seed_{SEED}"

    print("\n")
    print("#" * 80)
    print(f"STARTING MODEL: {model_name}")
    print(f"SEED: {SEED}")
    print("#" * 80)

    !python train.py \
        --img {IMGSZ} \
        --batch {BATCH} \
        --epochs {EPOCHS} \
        --optimizer {OPTIMIZER} \
        --data {DATA_YAML} \
        --weights {weights} \
        --name {run_name} \
        --seed {SEED}


# ============================================================
# 6. FINISHED
# ============================================================

print("\n")
print("=" * 80)
print("YOLOv5 TRAINING FINISHED")
print("=" * 80)